repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-builtin-literals
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: trailing-whitespace
      - id: flake8
        args:
          - --max-line-length=160
          - --exclude=*/migrations/*,docs/*
          - --ignore=E501
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: master
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: rst-backticks
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: master
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.8.0
    hooks:
      - id: seed-isort-config
        args:
          - --application-directories
          - mig3
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.18
    hooks:
      - id: isort
        additional_dependencies:
          - isort[pyproject]
  - repo: https://github.com/ambv/black
    rev: acafdcb5945cda8d424b2dbd0f9d0d56cf658533
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/bandit
    rev: 823138f418905a99fb7bbff8bb35b97f6dc9e5ab
    hooks:
      - id: bandit
        args:
          - -v
          - -c
          - bandit.yaml
          - -r
          - mig3
  - repo: https://github.com/PyCQA/pydocstyle
    rev: master
    hooks:
      - id: pydocstyle
