repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: flake8
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.8.0
    hooks:
      - id: seed-isort-config
        args: ["--application-directories", "mig3"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.18
    hooks:
      - id: isort
        additional_dependencies: ["isort[pyproject]",]
  - repo: https://github.com/ambv/black
    rev: acafdcb5945cda8d424b2dbd0f9d0d56cf658533
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/bandit
    rev: 823138f418905a99fb7bbff8bb35b97f6dc9e5ab
    hooks:
      - id: bandit
        args: ["-v", "-c", "bandit.yaml", "-r", "mig3"]
