dist: xenial
language: python
sudo: false
services:
  - postgresql
env:
  - "DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres"
python:
  - "3.7"
install:
    - 'pip install pipenv==2018.11.26'
    - 'pipenv install --dev'
    - 'barb -z'
script: 'python -m pytest'
