dist: xenial
language: python
python: 3.7
sudo: false

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

env:
  - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres

jobs:
  include:
    - stage: check
      name: fossa
      install:
        - pip install pip==19.1.1 poetry==0.12.17
      script:
        - poetry install --no-dev
        - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
        - pip freeze > requirements.txt
        - fossa analyze
    - install:
        - pip install pre-commit==1.18.0
        - pre-commit install
      name: lint
      script:
        - pre-commit run --all-files
    - services:
        - postgresql
      name: test
      install:
        - pip install pip==19.1.1 poetry==0.12.17
        - poetry install
      before_script:
        - barb -z
      script:
        - python -m pytest
      after_success:
        - pip install codacy-coverage==1.3.11
        - coverage xml
        - python-codacy-coverage -r coverage.xml
