dist: xenial
language: python
python: 3.7
sudo: false

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
    - $HOME/virtualenv/python3.7

env:
  - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres

jobs:
  include:
    - name: fossa
      install:
        - pip install pip==19.1.1 poetry==0.12.17
      script:
        - poetry install --no-dev
        - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
        - pip freeze > requirements.txt
        - fossa analyze
    - name: lint and test
      services:
        - postgresql
      install:
        - pip install poetry==0.12.17 pre-commit==1.18.0
        - poetry install
        - pre-commit install
      before_script:
        - barb -z
      script:
        - SKIP=isort pre-commit run --all-files
        - python -m pytest
      after_success:
        - pip install codacy-coverage==1.3.11
        - coverage xml
        - python-codacy-coverage -r coverage.xml
