version: "3.7"

services:
  db:
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 15432:5432
  backend:
    build:
      context: .
      dockerfile: docker/backend.dev.Dockerfile
    command: ./docker/runserver.sh
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - mig3-ui
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dev.Dockerfile
    command: yarn serve
    volumes:
      - ./mig3-ui:/code/
    ports:
      - 8080:8080

volumes:
  postgres_data:
