version: "3.7"

services:
  db:
    container_name: mig3-db
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 15432:5432
  backend:
    container_name: mig3-backend
    image: mig3-backend-dev
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
    volumes:
      - .:/data/mig3
    ports:
      - 8000:8000
    depends_on:
      - db
      - frontend
  frontend:
    container_name: mig3-frontend
    image: mig3-frontend-dev
    volumes:
      - ./mig3-ui/dist:/data/mig3/mig3-ui/dist
      - ./mig3-ui/public:/data/mig3/mig3-ui/public
      - ./mig3-ui/src:/data/mig3/mig3-ui/src
    ports:
      - 8080:8080

volumes:
  postgres_data:
