version: "3.7"

services:
  db:
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  mig3:
    build: .
    command: ./runserver.sh
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
    volumes:
      - ./mig3:/code/mig3
      - ./mig3-ui/dist:/code/mig3-ui/dist
    ports:
      - 8000:8000
    depends_on:
      - db
      - mig3-ui
  mig3-ui:
    build: mig3-ui
    command: yarn serve
    volumes:
      - ./mig3-ui:/code
      - ./mig3-ui/dist:/code/mig3-ui/dist
    ports:
      - 8080:8080

volumes:
  postgres_data:
