version: "3.7"

services:
  db:
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 15432:5432
  mig3:
    build: .
    command: ./runserver.sh
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - mig3-ui
  mig3-ui:
    build: mig3-ui
    command: ./serve.sh
    volumes:
      - ./mig3-ui:/code/
    ports:
      - 8080:8080

volumes:
  postgres_data:
