version: "3.7"

services:
  db:
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 15432:5432
  backend:
    build:
      context: .
      dockerfile: docker/backend.dev.Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
    command: docker/runserver.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - frontend
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dev.Dockerfile
    volumes:
      - ./mig3-ui/dist:/code/dist
      - ./mig3-ui/public:/code/public
      - ./mig3-ui/src:/code/src
    ports:
      - 8080:8080

volumes:
  postgres_data:
