# Generated by Django 2.2.1 on 2019-05-01 17:36

import django_fsm
from django.db import migrations

import builds.models


class Migration(migrations.Migration):

    dependencies = [("builds", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="testoutcome",
            name="result",
            field=django_fsm.FSMIntegerField(
                choices=[(0, "Error"), (1, "Failed"), (2, "Passed"), (3, "Skipped"), (4, "XFailed")],
                default=builds.models.TestOutcome.Results(0),
            ),
        )
    ]
