# Generated by Django 2.2.1 on 2019-05-02 01:52

from django.db import migrations

import builds.models


class Migration(migrations.Migration):

    dependencies = [("builds", "0002_auto_20190501_1736")]

    operations = [migrations.AlterModelManagers(name="build", managers=[("objects", builds.models.BuildManager())])]
