# Generated by Django 2.2.1 on 2019-05-02 02:13
import django_fsm
from django.db import migrations
from django_choices_enum import ChoicesEnum


class Results(int, ChoicesEnum):
    ERROR = (0, "Error")
    FAILED = (1, "Failed")
    PASSED = (2, "Passed")
    SKIPPED = (3, "Skipped")
    XFAILED = (4, "XFailed")

    @classmethod
    def exclude(cls, *excluded):
        return [member for member in cls if member not in excluded]


class Migration(migrations.Migration):

    dependencies = [("builds", "0003_auto_20190502_0152")]

    operations = [
        migrations.AlterField(
            model_name="testoutcome",
            name="result",
            field=django_fsm.FSMIntegerField(choices=Results.choices(), default=Results(0), protected=True),
        )
    ]
