version: 2.1

executors:
  docker:
    docker:
      - image: circleci/docker:latest
    working_directory: ~/code
    environment:
      PROGRESS: plain
  nodejs:
    docker:
      - image: circleci/node:12.10-browsers
    working_directory: ~/code

jobs:
  test-frontend-build:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "mig3-ui/package.json" }}
            - v1-dependencies-
      - run: cd mig3-ui && yarn install
      - save_cache:
          paths:
            - mig3-ui/node_modules
          key: v1-dependencies-{{ checksum "mig3-ui/package.json" }}
      - run: cd mig3-ui && yarn build

  test-dev-environment-build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: make help
      - run: make devserver && make clean

  test-dev-environment-nuclear-option:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "mig3-ui/package.json" }}
            - v1-dependencies-
      - run: make devserver && make nuclear-option

workflows:
  frontend:
    jobs:
      - test-frontend-build
  dev-environment:
    jobs:
      - test-dev-environment-build
      - test-dev-environment-nuclear-option
