version: 2.1

executors:
  docker:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/mig3
    environment:
      PROGRESS: plain
  nodejs:
    docker:
      - image: circleci/node:12.10-browsers
    working_directory: ~/mig3

jobs:
  test-frontend-build:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "mig3-ui/package.json" }}
            - v1-dependencies-
      - run: cd mig3-ui && yarn install
      - save_cache:
          paths:
            - mig3-ui/node_modules
          key: v1-dependencies-{{ checksum "mig3-ui/package.json" }}
      - run: cd mig3-ui && yarn build

  test-dev-environment-build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: make help
      - run: make mountless-devserver && make clean

  test-dev-environment-nuclear-option:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "mig3-ui/package.json" }}
            - v1-dependencies-
      - run: make mountless-devserver && make nuclear-option

  test-distribution:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build distribution image
          command: DOCKER_BUILDKIT=1 docker build . --progress=plain

workflows:
  frontend:
    jobs:
      - test-frontend-build
  dev-environment:
    jobs:
      - test-dev-environment-build
      - test-dev-environment-nuclear-option
  distribution:
    jobs:
      - test-distribution
